USE  vendas_sucos;

SELECT A.NUMERO FROM NOTAS A
INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE <= 18;

DELETE A  FROM NOTAS A INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE <= 18 ;

SELECT DISTINCT  A.CPF ,A.NUMERO, B.NOME, A.MATRICULA FROM NOTAS A
INNER JOIN CLIENTES B ON A.CPF = B.CPF
WHERE B.IDADE > 18;
