USE vendas_sucos;

SELECT A.CPF FROM CLIENTES A
INNER JOIN VENDEDORES B
ON A.BAIRRO = B.BAIRRO;

SELECT distinct * FROM CLIENTES A INNER JOIN sucos_vendas.tabela_de_vendedores B
INNER JOIN VENDEDORES B ;

UPDATE  CLIENTES A INNER JOIN sucos_vendas.tabela_de_vendedores B
ON (A.BAIRRO = B.BAIRRO)
SET  A.VOLUME_COMPRA = A.VOLUME_COMPRA*1.3  ;