USE vendas_sucos;

CREATE TABLE `PRODUTOS2` (
  `CODIGO` varchar(10) NOT NULL,
  `DESCRITOR` varchar(100) DEFAULT NULL,
  `SABOR` varchar(50) DEFAULT NULL,
  `TAMANHO` varchar(50) DEFAULT NULL,
  `EMBALAGEM` varchar(50) DEFAULT NULL,
  `PRECO_LISTA` float DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ;
 SELECT * FROM PRODUTOS2;
 
 INSERT INTO PRODUTOS2
 SELECT * FROM PRODUTOS;
 
 DELETE FROM PRODUTOS2;