USE vendas_sucos;
SELECT * FROM sucos_vendas.tabela_de_clientes;

INSERT INTO CLIENTES
(CPF,NOME,ENDERECO,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA)

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP,DATA_DE_NASCIMENTO AS  DATA_NASCIMENTO, IDADE, SEXO,LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA,PRIMEIRA_COMPRA 

FROM sucos_vendas.tabela_de_clientes 

WHERE CPF NOT IN (SELECT CPF FROM CLIENTES);


SELECT * FROM vendas_sucos.CLIENTES;