

CREATE TABLE TAB_IDENTIFY(ID INT auto_increment, DESCRITOR VARCHAR(20),PRIMARY KEY(ID));

INSERT INTO TAB_IDENTIFY (DESCRITOR) VALUES ('CLIENTE1');

INSERT INTO TAB_IDENTIFY (DESCRITOR) VALUES ('CLIENTE2');

INSERT INTO TAB_IDENTIFY (DESCRITOR) VALUES ('CLIENTE3');


INSERT INTO TAB_IDENTIFY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE4');

DELETE FROM TAB_IDENTIFY WHERE ID = 3;

INSERT INTO TAB_IDENTIFY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE6');

INSERT INTO TAB_IDENTIFY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE7');

DELETE FROM TAB_IDENTIFY WHERE ID = 2;

SELECT * FROM  TAB_IDENTIFY;
