
SELECT CONCAT('O dia de hoje é: ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O ano de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%m/%y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%d/%m/%Y') ) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(),'%d/%m/%Y - %U') ) AS RESULTADO;

SELECT CONVERT(23.3, CHAR) AS RESULTADO;

SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;

SELECT CONCAT('O cliente ',NOME,'  faturou:',FLOOR(QUANTIDADE * PRECO),
' no ano de ',YEAR(DATA_VENDA)) AS RESULTADO , YEAR(DATA_VENDA),FLOOR(QUANTIDADE * PRECO) AS FATURAMENTO,
NOME FROM itens_notas_fiscais INF INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF WHERE YEAR(DATA_VENDA) = 2016 ;
