
SELECT * FROM NOTAS;
SELECT * FROM ITENS_NOTAS;
SELECT * FROM TAB_FATURAMENTO;

UPDATE ITENS_NOTAS SET QUANTIDADE = 200
WHERE NUMERO = '0104' AND CODIGO = '1000889';

DELETE FROM ITENS_NOTAS WHERE NUMERO = '0104' AND CODIGO = '1000889';

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_UPDATE AFTER UPDATE ON ITENS_NOTAS
FOR EACH ROW BEGIN
   DELETE FROM TAB_FATURAMENTO;
   INSERT INTO TAB_FATURAMENTO
   SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM
   NOTAS A INNER JOIN ITENS_NOTAS B ON A.NUMERO = B.NUMERO
   GROUP BY A.DATA_VENDA ;
END //

DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DELETE AFTER DELETE ON ITENS_NOTAS
FOR EACH ROW BEGIN
   DELETE FROM TAB_FATURAMENTO;
   INSERT INTO TAB_FATURAMENTO
   SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM
   NOTAS A INNER JOIN ITENS_NOTAS B ON A.NUMERO = B.NUMERO
   GROUP BY A.DATA_VENDA ;
END //


INSERT INTO NOTAS(NUMERO, DATA_VENDA, CPF, MATRICULA,IMPOSTO)
VALUES('0106','2021-04-01','1471156710' , '235',0.10);

INSERT INTO ITENS_NOTAS (NUMERO,CODIGO,QUANTIDADE,PRECO)
VALUES('0106','1000889',100,10);

SELECT * FROM TAB_FATURAMENTO;

DELETE FROM ITENS_NOTAS WHERE NUMERO = '0104' AND CODIGO = '1000889';

SELECT * FROM ITENS_NOTAS;

UPDATE ITENS_NOTAS SET QUANTIDADE = 400
WHERE NUMERO = '0102' AND CODIGO = '1000889';